name: Flutter CI

on: 
  [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter version: '3.7.7'
      - run: |
             cd android_projects
             flutter pub get
             flutter build apk --release --no-sound-null-safety
